version: '3'
services:
    2020DhbWeb1:
      build: .           # 构建路径, . 表示会在当前路径下找 Dockerfile 文件
      image: 2020dhbweb1   # 镜像名称, 如果没有上面的 build, docker-compose 将会尝试从官方仓库 pull 该镜像
      ports: 
        - 80:80     # 映射端口 虚拟机端口:容器内端口
      links:
        - dhb1mysql:mysql
    dhb1mysql:
      build: ./mysql
      image: 2020dhbwebsql
      environment:
        MYSQL_ROOT_PASSWORD: "root"