version: '3'
services:
    2020DhbWeb1 : 
      build: .
      image: 2020dhbweb1
      ports:
        - 80:80
      links:
        - mysql:mysql
    mysql : 
      build: ./mysql
      image: 2020dhbwebsql
      environment:
        MYSQL_ROOT_PASSWORD: "root"